config/routes.rb
Rails.application.routes.draw do
  resources :arts
  root "arts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: %i[ show edit update destroy ]

  # GET /arts or /arts.json
  def index
    @arts = Art.all
    @hostname = Socket.gethostname
    @database_adapter = ActiveRecord::Base.connection.adapter_name
  end

  # GET /arts/1 or /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts or /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to art_url(@art), notice: "Art was successfully created." }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1 or /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to art_url(@art), notice: "Art was successfully updated." }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1 or /arts/1.json
  def destroy
    @art.destroy!

    respond_to do |format|
      format.html { redirect_to arts_url, notice: "Art was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def art_params
      params.require(:art).permit(:title, :description, :artist, :year, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_art.html.erb
<div id="<%= dom_id art %>">
  <p>
    <strong>Title:</strong>
    <%= art.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= art.description %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= art.artist %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= art.year %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= art.image_url %>
  </p>

</div>

app/views/arts/_form.html.erb
<%= form_with(model: art) do |form| %>
  <% if art.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
        <% art.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing art</h1>

<%= render "form", art: @art %>

<br>

<div>
  <%= link_to "Show this piece", @art %> |
  <%= link_to "Back to gallery", arts_path %>
</div>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="header">My Art Gallery</h1>
<h2>testing full pipeline deployment new attempt jotain vielä</h2>



<div class="gallery">
  <% if @arts.length == 0 %>
    <div class="empty">

      <div class="empty_frame frame shadow">
        &nbsp;
      </div>

      <div>
        <br/>
        The gallery is empty!  <%= link_to  'Add a work', new_art_path %> to get started.
      </div>
    </div>
  <% else %>
    <% @arts.each do |art| %>
      <div class="art">
        <div class="frame_holder">
          <%= image_tag(art.image_url, class:"frame shadow") %>
        </div>
        <div class="info_holder">
          <div class="info shadow">
            <div class="art_title"><%= art.title %></div>
            <div><%= art.artist %></div>
            <div><%= art.year %></div>
            <%= link_to 'Delete', art, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>    
    <% end %> 
  <% end %>
</div>

<% if @arts.length != 0 %>
  <div>
    <%= link_to  'Add to Your Collection', new_art_path %>
  </div> 
<% end %>


<div>
<br/>
Hostname: <%= @hostname %><br/>
RAILS_ENV: <%= ENV['RAILS_ENV'] %><br/>
Database Adapter: <%= @database_adapter %>
</div>

app/views/arts/new.html.erb
<h1>New art</h1>

<%= render "form", art: @art %>

<br>

<div>
  <%= link_to "Back to gallery", arts_path %>
</div>

app/views/arts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @art %>

<div>
  <%= link_to "Edit this piece", edit_art_path(@art) %> |
  <%= link_to "Back to gallery", arts_path %>

  <%= button_to "Destroy this piece", @art, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>